//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonTreeView.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonTreeView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse All 的本地化字符串。
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Node 的本地化字符串。
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion action failed 的本地化字符串。
        /// </summary>
        internal static string DeletionActionFailed {
            get {
                return ResourceManager.GetString("DeletionActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand All 的本地化字符串。
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Array 的本地化字符串。
        /// </summary>
        internal static string InsertArray {
            get {
                return ResourceManager.GetString("InsertArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Object 的本地化字符串。
        /// </summary>
        internal static string InsertObject {
            get {
                return ResourceManager.GetString("InsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Property as Array 的本地化字符串。
        /// </summary>
        internal static string InsertPropertyAsArray {
            get {
                return ResourceManager.GetString("InsertPropertyAsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Property as Object 的本地化字符串。
        /// </summary>
        internal static string InsertPropertyAsObject {
            get {
                return ResourceManager.GetString("InsertPropertyAsObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Property as Value 的本地化字符串。
        /// </summary>
        internal static string InsertPropertyAsValue {
            get {
                return ResourceManager.GetString("InsertPropertyAsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Value 的本地化字符串。
        /// </summary>
        internal static string InsertValue {
            get {
                return ResourceManager.GetString("InsertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json Array 的本地化字符串。
        /// </summary>
        internal static string JsonArray {
            get {
                return ResourceManager.GetString("JsonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json Object 的本地化字符串。
        /// </summary>
        internal static string JsonObject {
            get {
                return ResourceManager.GetString("JsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Json Object 的本地化字符串。
        /// </summary>
        internal static string NewJsonObject {
            get {
                return ResourceManager.GetString("NewJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste action failed 的本地化字符串。
        /// </summary>
        internal static string PasteActionFailed {
            get {
                return ResourceManager.GetString("PasteActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Node After 的本地化字符串。
        /// </summary>
        internal static string PasteNodeAfter {
            get {
                return ResourceManager.GetString("PasteNodeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Node Before 的本地化字符串。
        /// </summary>
        internal static string PasteNodeBefore {
            get {
                return ResourceManager.GetString("PasteNodeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
    }
}
